# Arquivo de configuração da medição de camada limite com o Pitot

# Informações sobre a medição
[profile]
# Fator de escala do modelo
scale = 0.005
# Altura de referência do modelo
href = 700
# Unidade usada para especificar o modelo
unit = "mm"
# Altura da base (zero) no modelo para que haja correspondência
# com o desenho do edifício ou modelo FEM do edifício
alt = 0

# Eixo que será medido
# Caso seja um array, teremos um grid. A ordem especificará qual direção
# é percorrida inicialmente. Veja outro exemplo
axes = "z"

# Massa específica do ar. Pode ser um valor fixo (caso seja numérico) ou um
# outro campo, com nome
# Neste caso, usamos um valor fixo
rho = 1.08



# Configuração do túnel de vento
# coisas como altura e espaçamento da rugosidade, geradores de vórtice
# e comprimento do piso rugoso.
[tunnel]
# Altura dos elementos de rugosidade (mm)
H = 80
# Comprimento do piso rugos (m)
L = 20

# Padrão geométrico de como os elementos rugosos estão distribuídos
distr = "diamante"

# Como o perfil de velocidade é gerado
method = "Counihan, 1.2 m"


# Configuração da plotagem
# Isso vai mudar com o tempo.
[plot]
# Plotar a altura da rugosidade?
rough = true

# Plotar a altura de referência
ref = true



# O que vamos calcular com este perfil
# Caso tenha mais de um elemento no array `[[calc]]',
# podemos calcular as coisas para cada perfil
[[calc]]
# Pitot usado para medir o perfil
profile = "pitot"
# Pitot usado para medir pressão dinâmica de referência
ref = "ref"

# Corrigir os dados com a pressão dinâmica de referência?
refcorrection = true

# Medir camada logarítmica/z0?
log = true

# Medir o perfil potencial?
power = true

# Índice das seções usadas para calcular as característics do perfil
# Se não for especificado, será calculado para cada 
cases = [1,2]



# Em geral não dá para medir o perfil com apenas uma única medição.
# Então temos que medir por trechos. Cada trecho é especificado em uma única
# `[[section]]`
[[section]]
# Nome/sufixo para a seção. Pode não ser nada se for uma única seção.
# Se `name` não for definido uma seção, `name = ""`. Caso, tenha mais de uma
# seção e `name` não seja definido, `-1`, `-2` será usado como name.
name = "-lo"
# Referência. O atuador será programado na posição `z - ref`
# Caso seja um grid, isto deve ser um array com a referência de cada eixo na ordem
# do campo `axes` acima
ref = 0
# Cada eixo deve ser especificado a seguir com o nome correspondendo a um dos campos
# de `axes` axima
z = [10, 20, 30, 40, 50, 60, 80, 100, 120, 140, 160, 180, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560]

[[section]]
name = "-hi"
ref = 0
z = [600, 640, 680, 720, 760, 800, 850, 900, 950, 1000, 1050, 1100, 1150]





# Especificação dos tubos de Pitot utilizados
# Estamos usando dois tubos de Pitot, um para medir o perfil e outro de referência
# Primeiro o tubo de Pitot para medir o Perfil
[[pitot]]
name = "pitot" # Nome do dispositivo 
type = "Prandtl" # Tipo de sensor
Cd = 0.997 # Coeficiente de descarga do sensor ou outros parâmetros do Pitot
channels = [13,14]

[[pitot]]
name = "ref"
type = "Prandtl"
Cd = 0.997
channels = [15,16]


# Dispositivo de medição de pressão
[device]
type = "DSA3217"
name = "pitot"
ip = "191.30.80.131"
channels = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

# Configuração do dispositivo para a medição do perfil
[device.config]
AVG=200
PERIOD=500
FPS=20

# Configuração do dispositivo para testes (sem medição formal)
[device.testconfig]
AVG=200
PERIOD=500
FPS=4


# Atuador que vai movimentar o tubo de Pitot
[actuator]
type = "RoboSimples"
name = "Robo"
ip = "192.168.0.50"
port = 9543
axes = ["z"]



